/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { AssetCreationTimeSeriesPointDto } from '../models';
// @ts-ignore
import type { AssetResponseDto } from '../models';
// @ts-ignore
import type { CreateAssetDto } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { UpdateAssetDto } from '../models';
/**
 * AssetsApi - axios parameter creator
 * @export
 */
export const AssetsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Creates a new asset in the database.
     * @param {CreateAssetDto} createAssetDto Data for the new asset.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerCreate: async (
      createAssetDto: CreateAssetDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createAssetDto' is not null or undefined
      assertParamExists('assetsControllerCreate', 'createAssetDto', createAssetDto);
      const localVarPath = `/assets`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createAssetDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Returns a list of all assets in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/assets`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Returns a single instance of an Asset.
     * @param {number} id Unique asset identifier in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerFindOne: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('assetsControllerFindOne', 'id', id);
      const localVarPath = `/assets/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Frees an asset from the employee assigned.
     * @param {number} id Unique asset identifier in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerFreeAsset: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('assetsControllerFreeAsset', 'id', id);
      const localVarPath = `/assets/{id}/free`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Returns monthly counts of assets created in the given calendar year.
     * @param {number} year Calendar year to aggregate (e.g. 2024).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerGetAssetCreationTimeSeriesByYear: async (
      year: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'year' is not null or undefined
      assertParamExists('assetsControllerGetAssetCreationTimeSeriesByYear', 'year', year);
      const localVarPath = `/assets/creation-timeseries/{year}`.replace(
        `{${'year'}}`,
        encodeURIComponent(String(year)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Soft deletes the asset from the database.
     * @param {number} id Unique asset identifier in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerRemove: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('assetsControllerRemove', 'id', id);
      const localVarPath = `/assets/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Updates an already existing Asset.
     * @param {number} id Unique asset identifier in the database.
     * @param {UpdateAssetDto} updateAssetDto New data for the Asset.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerUpdate: async (
      id: number,
      updateAssetDto: UpdateAssetDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('assetsControllerUpdate', 'id', id);
      // verify required parameter 'updateAssetDto' is not null or undefined
      assertParamExists('assetsControllerUpdate', 'updateAssetDto', updateAssetDto);
      const localVarPath = `/assets/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateAssetDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AssetsApi - functional programming interface
 * @export
 */
export const AssetsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AssetsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Creates a new asset in the database.
     * @param {CreateAssetDto} createAssetDto Data for the new asset.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async assetsControllerCreate(
      createAssetDto: CreateAssetDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AssetResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.assetsControllerCreate(
        createAssetDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AssetsApi.assetsControllerCreate']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Returns a list of all assets in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async assetsControllerFindAll(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AssetResponseDto>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.assetsControllerFindAll(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AssetsApi.assetsControllerFindAll']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Returns a single instance of an Asset.
     * @param {number} id Unique asset identifier in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async assetsControllerFindOne(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AssetResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.assetsControllerFindOne(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AssetsApi.assetsControllerFindOne']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Frees an asset from the employee assigned.
     * @param {number} id Unique asset identifier in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async assetsControllerFreeAsset(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.assetsControllerFreeAsset(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AssetsApi.assetsControllerFreeAsset']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Returns monthly counts of assets created in the given calendar year.
     * @param {number} year Calendar year to aggregate (e.g. 2024).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async assetsControllerGetAssetCreationTimeSeriesByYear(
      year: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<AssetCreationTimeSeriesPointDto>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.assetsControllerGetAssetCreationTimeSeriesByYear(
          year,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AssetsApi.assetsControllerGetAssetCreationTimeSeriesByYear']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Soft deletes the asset from the database.
     * @param {number} id Unique asset identifier in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async assetsControllerRemove(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.assetsControllerRemove(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AssetsApi.assetsControllerRemove']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Updates an already existing Asset.
     * @param {number} id Unique asset identifier in the database.
     * @param {UpdateAssetDto} updateAssetDto New data for the Asset.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async assetsControllerUpdate(
      id: number,
      updateAssetDto: UpdateAssetDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AssetResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.assetsControllerUpdate(
        id,
        updateAssetDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AssetsApi.assetsControllerUpdate']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * AssetsApi - factory interface
 * @export
 */
export const AssetsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = AssetsApiFp(configuration);
  return {
    /**
     *
     * @summary Creates a new asset in the database.
     * @param {AssetsApiAssetsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerCreate(
      requestParameters: AssetsApiAssetsControllerCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AssetResponseDto> {
      return localVarFp
        .assetsControllerCreate(requestParameters.createAssetDto, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Returns a list of all assets in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerFindAll(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<AssetResponseDto>> {
      return localVarFp
        .assetsControllerFindAll(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Returns a single instance of an Asset.
     * @param {AssetsApiAssetsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerFindOne(
      requestParameters: AssetsApiAssetsControllerFindOneRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AssetResponseDto> {
      return localVarFp
        .assetsControllerFindOne(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Frees an asset from the employee assigned.
     * @param {AssetsApiAssetsControllerFreeAssetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerFreeAsset(
      requestParameters: AssetsApiAssetsControllerFreeAssetRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<MessageResponseDto> {
      return localVarFp
        .assetsControllerFreeAsset(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Returns monthly counts of assets created in the given calendar year.
     * @param {AssetsApiAssetsControllerGetAssetCreationTimeSeriesByYearRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerGetAssetCreationTimeSeriesByYear(
      requestParameters: AssetsApiAssetsControllerGetAssetCreationTimeSeriesByYearRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<AssetCreationTimeSeriesPointDto>> {
      return localVarFp
        .assetsControllerGetAssetCreationTimeSeriesByYear(requestParameters.year, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Soft deletes the asset from the database.
     * @param {AssetsApiAssetsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerRemove(
      requestParameters: AssetsApiAssetsControllerRemoveRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<MessageResponseDto> {
      return localVarFp
        .assetsControllerRemove(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Updates an already existing Asset.
     * @param {AssetsApiAssetsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    assetsControllerUpdate(
      requestParameters: AssetsApiAssetsControllerUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AssetResponseDto> {
      return localVarFp
        .assetsControllerUpdate(requestParameters.id, requestParameters.updateAssetDto, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AssetsApi - interface
 * @export
 * @interface AssetsApi
 */
export interface AssetsApiInterface {
  /**
   *
   * @summary Creates a new asset in the database.
   * @param {AssetsApiAssetsControllerCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApiInterface
   */
  assetsControllerCreate(
    requestParameters: AssetsApiAssetsControllerCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<AssetResponseDto>;

  /**
   *
   * @summary Returns a list of all assets in the database.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApiInterface
   */
  assetsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<AssetResponseDto>>;

  /**
   *
   * @summary Returns a single instance of an Asset.
   * @param {AssetsApiAssetsControllerFindOneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApiInterface
   */
  assetsControllerFindOne(
    requestParameters: AssetsApiAssetsControllerFindOneRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<AssetResponseDto>;

  /**
   *
   * @summary Frees an asset from the employee assigned.
   * @param {AssetsApiAssetsControllerFreeAssetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApiInterface
   */
  assetsControllerFreeAsset(
    requestParameters: AssetsApiAssetsControllerFreeAssetRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<MessageResponseDto>;

  /**
   *
   * @summary Returns monthly counts of assets created in the given calendar year.
   * @param {AssetsApiAssetsControllerGetAssetCreationTimeSeriesByYearRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApiInterface
   */
  assetsControllerGetAssetCreationTimeSeriesByYear(
    requestParameters: AssetsApiAssetsControllerGetAssetCreationTimeSeriesByYearRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Array<AssetCreationTimeSeriesPointDto>>;

  /**
   *
   * @summary Soft deletes the asset from the database.
   * @param {AssetsApiAssetsControllerRemoveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApiInterface
   */
  assetsControllerRemove(
    requestParameters: AssetsApiAssetsControllerRemoveRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<MessageResponseDto>;

  /**
   *
   * @summary Updates an already existing Asset.
   * @param {AssetsApiAssetsControllerUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApiInterface
   */
  assetsControllerUpdate(
    requestParameters: AssetsApiAssetsControllerUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<AssetResponseDto>;
}

/**
 * Request parameters for assetsControllerCreate operation in AssetsApi.
 * @export
 * @interface AssetsApiAssetsControllerCreateRequest
 */
export interface AssetsApiAssetsControllerCreateRequest {
  /**
   * Data for the new asset.
   * @type {CreateAssetDto}
   * @memberof AssetsApiAssetsControllerCreate
   */
  readonly createAssetDto: CreateAssetDto;
}

/**
 * Request parameters for assetsControllerFindOne operation in AssetsApi.
 * @export
 * @interface AssetsApiAssetsControllerFindOneRequest
 */
export interface AssetsApiAssetsControllerFindOneRequest {
  /**
   * Unique asset identifier in the database.
   * @type {number}
   * @memberof AssetsApiAssetsControllerFindOne
   */
  readonly id: number;
}

/**
 * Request parameters for assetsControllerFreeAsset operation in AssetsApi.
 * @export
 * @interface AssetsApiAssetsControllerFreeAssetRequest
 */
export interface AssetsApiAssetsControllerFreeAssetRequest {
  /**
   * Unique asset identifier in the database.
   * @type {number}
   * @memberof AssetsApiAssetsControllerFreeAsset
   */
  readonly id: number;
}

/**
 * Request parameters for assetsControllerGetAssetCreationTimeSeriesByYear operation in AssetsApi.
 * @export
 * @interface AssetsApiAssetsControllerGetAssetCreationTimeSeriesByYearRequest
 */
export interface AssetsApiAssetsControllerGetAssetCreationTimeSeriesByYearRequest {
  /**
   * Calendar year to aggregate (e.g. 2024).
   * @type {number}
   * @memberof AssetsApiAssetsControllerGetAssetCreationTimeSeriesByYear
   */
  readonly year: number;
}

/**
 * Request parameters for assetsControllerRemove operation in AssetsApi.
 * @export
 * @interface AssetsApiAssetsControllerRemoveRequest
 */
export interface AssetsApiAssetsControllerRemoveRequest {
  /**
   * Unique asset identifier in the database.
   * @type {number}
   * @memberof AssetsApiAssetsControllerRemove
   */
  readonly id: number;
}

/**
 * Request parameters for assetsControllerUpdate operation in AssetsApi.
 * @export
 * @interface AssetsApiAssetsControllerUpdateRequest
 */
export interface AssetsApiAssetsControllerUpdateRequest {
  /**
   * Unique asset identifier in the database.
   * @type {number}
   * @memberof AssetsApiAssetsControllerUpdate
   */
  readonly id: number;

  /**
   * New data for the Asset.
   * @type {UpdateAssetDto}
   * @memberof AssetsApiAssetsControllerUpdate
   */
  readonly updateAssetDto: UpdateAssetDto;
}

/**
 * AssetsApi - object-oriented interface
 * @export
 * @class AssetsApi
 * @extends {BaseAPI}
 */
export class AssetsApi extends BaseAPI implements AssetsApiInterface {
  /**
   *
   * @summary Creates a new asset in the database.
   * @param {AssetsApiAssetsControllerCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApi
   */
  public assetsControllerCreate(
    requestParameters: AssetsApiAssetsControllerCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AssetsApiFp(this.configuration)
      .assetsControllerCreate(requestParameters.createAssetDto, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Returns a list of all assets in the database.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApi
   */
  public assetsControllerFindAll(options?: RawAxiosRequestConfig) {
    return AssetsApiFp(this.configuration)
      .assetsControllerFindAll(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Returns a single instance of an Asset.
   * @param {AssetsApiAssetsControllerFindOneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApi
   */
  public assetsControllerFindOne(
    requestParameters: AssetsApiAssetsControllerFindOneRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AssetsApiFp(this.configuration)
      .assetsControllerFindOne(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Frees an asset from the employee assigned.
   * @param {AssetsApiAssetsControllerFreeAssetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApi
   */
  public assetsControllerFreeAsset(
    requestParameters: AssetsApiAssetsControllerFreeAssetRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AssetsApiFp(this.configuration)
      .assetsControllerFreeAsset(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Returns monthly counts of assets created in the given calendar year.
   * @param {AssetsApiAssetsControllerGetAssetCreationTimeSeriesByYearRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApi
   */
  public assetsControllerGetAssetCreationTimeSeriesByYear(
    requestParameters: AssetsApiAssetsControllerGetAssetCreationTimeSeriesByYearRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AssetsApiFp(this.configuration)
      .assetsControllerGetAssetCreationTimeSeriesByYear(requestParameters.year, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Soft deletes the asset from the database.
   * @param {AssetsApiAssetsControllerRemoveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApi
   */
  public assetsControllerRemove(
    requestParameters: AssetsApiAssetsControllerRemoveRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AssetsApiFp(this.configuration)
      .assetsControllerRemove(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Updates an already existing Asset.
   * @param {AssetsApiAssetsControllerUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AssetsApi
   */
  public assetsControllerUpdate(
    requestParameters: AssetsApiAssetsControllerUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AssetsApiFp(this.configuration)
      .assetsControllerUpdate(requestParameters.id, requestParameters.updateAssetDto, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
