/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { CategoryResponseDto } from '../models';
// @ts-ignore
import type { CreateCategoryDto } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { UpdateCategoryDto } from '../models';
/**
 * CategoriesApi - axios parameter creator
 * @export
 */
export const CategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Create a new category
     * @param {CreateCategoryDto} createCategoryDto The data for the new category
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerCreate: async (
      createCategoryDto: CreateCategoryDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createCategoryDto' is not null or undefined
      assertParamExists('categoriesControllerCreate', 'createCategoryDto', createCategoryDto);
      const localVarPath = `/categories`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createCategoryDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Gets all categories from the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerFindAll: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/categories`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Finds a single category.
     * @param {number} id Unique identifier of the category.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerFindOne: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('categoriesControllerFindOne', 'id', id);
      const localVarPath = `/categories/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Removes logically a category.
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerRemove: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('categoriesControllerRemove', 'id', id);
      const localVarPath = `/categories/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Updates a single category.
     * @param {number} id Unique identifier for the category.
     * @param {UpdateCategoryDto} updateCategoryDto New data for the category.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerUpdate: async (
      id: number,
      updateCategoryDto: UpdateCategoryDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('categoriesControllerUpdate', 'id', id);
      // verify required parameter 'updateCategoryDto' is not null or undefined
      assertParamExists('categoriesControllerUpdate', 'updateCategoryDto', updateCategoryDto);
      const localVarPath = `/categories/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateCategoryDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CategoriesApi - functional programming interface
 * @export
 */
export const CategoriesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = CategoriesApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Create a new category
     * @param {CreateCategoryDto} createCategoryDto The data for the new category
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async categoriesControllerCreate(
      createCategoryDto: CreateCategoryDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoryResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerCreate(
        createCategoryDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CategoriesApi.categoriesControllerCreate']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Gets all categories from the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async categoriesControllerFindAll(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CategoryResponseDto>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.categoriesControllerFindAll(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CategoriesApi.categoriesControllerFindAll']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Finds a single category.
     * @param {number} id Unique identifier of the category.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async categoriesControllerFindOne(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoryResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerFindOne(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CategoriesApi.categoriesControllerFindOne']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Removes logically a category.
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async categoriesControllerRemove(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerRemove(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CategoriesApi.categoriesControllerRemove']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Updates a single category.
     * @param {number} id Unique identifier for the category.
     * @param {UpdateCategoryDto} updateCategoryDto New data for the category.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async categoriesControllerUpdate(
      id: number,
      updateCategoryDto: UpdateCategoryDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoryResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerUpdate(
        id,
        updateCategoryDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['CategoriesApi.categoriesControllerUpdate']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * CategoriesApi - factory interface
 * @export
 */
export const CategoriesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = CategoriesApiFp(configuration);
  return {
    /**
     *
     * @summary Create a new category
     * @param {CategoriesApiCategoriesControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerCreate(
      requestParameters: CategoriesApiCategoriesControllerCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CategoryResponseDto> {
      return localVarFp
        .categoriesControllerCreate(requestParameters.createCategoryDto, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Gets all categories from the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerFindAll(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<CategoryResponseDto>> {
      return localVarFp
        .categoriesControllerFindAll(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Finds a single category.
     * @param {CategoriesApiCategoriesControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerFindOne(
      requestParameters: CategoriesApiCategoriesControllerFindOneRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CategoryResponseDto> {
      return localVarFp
        .categoriesControllerFindOne(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Removes logically a category.
     * @param {CategoriesApiCategoriesControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerRemove(
      requestParameters: CategoriesApiCategoriesControllerRemoveRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<MessageResponseDto> {
      return localVarFp
        .categoriesControllerRemove(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Updates a single category.
     * @param {CategoriesApiCategoriesControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoriesControllerUpdate(
      requestParameters: CategoriesApiCategoriesControllerUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CategoryResponseDto> {
      return localVarFp
        .categoriesControllerUpdate(
          requestParameters.id,
          requestParameters.updateCategoryDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CategoriesApi - interface
 * @export
 * @interface CategoriesApi
 */
export interface CategoriesApiInterface {
  /**
   *
   * @summary Create a new category
   * @param {CategoriesApiCategoriesControllerCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApiInterface
   */
  categoriesControllerCreate(
    requestParameters: CategoriesApiCategoriesControllerCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CategoryResponseDto>;

  /**
   *
   * @summary Gets all categories from the database.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApiInterface
   */
  categoriesControllerFindAll(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Array<CategoryResponseDto>>;

  /**
   *
   * @summary Finds a single category.
   * @param {CategoriesApiCategoriesControllerFindOneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApiInterface
   */
  categoriesControllerFindOne(
    requestParameters: CategoriesApiCategoriesControllerFindOneRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CategoryResponseDto>;

  /**
   *
   * @summary Removes logically a category.
   * @param {CategoriesApiCategoriesControllerRemoveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApiInterface
   */
  categoriesControllerRemove(
    requestParameters: CategoriesApiCategoriesControllerRemoveRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<MessageResponseDto>;

  /**
   *
   * @summary Updates a single category.
   * @param {CategoriesApiCategoriesControllerUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApiInterface
   */
  categoriesControllerUpdate(
    requestParameters: CategoriesApiCategoriesControllerUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<CategoryResponseDto>;
}

/**
 * Request parameters for categoriesControllerCreate operation in CategoriesApi.
 * @export
 * @interface CategoriesApiCategoriesControllerCreateRequest
 */
export interface CategoriesApiCategoriesControllerCreateRequest {
  /**
   * The data for the new category
   * @type {CreateCategoryDto}
   * @memberof CategoriesApiCategoriesControllerCreate
   */
  readonly createCategoryDto: CreateCategoryDto;
}

/**
 * Request parameters for categoriesControllerFindOne operation in CategoriesApi.
 * @export
 * @interface CategoriesApiCategoriesControllerFindOneRequest
 */
export interface CategoriesApiCategoriesControllerFindOneRequest {
  /**
   * Unique identifier of the category.
   * @type {number}
   * @memberof CategoriesApiCategoriesControllerFindOne
   */
  readonly id: number;
}

/**
 * Request parameters for categoriesControllerRemove operation in CategoriesApi.
 * @export
 * @interface CategoriesApiCategoriesControllerRemoveRequest
 */
export interface CategoriesApiCategoriesControllerRemoveRequest {
  /**
   *
   * @type {number}
   * @memberof CategoriesApiCategoriesControllerRemove
   */
  readonly id: number;
}

/**
 * Request parameters for categoriesControllerUpdate operation in CategoriesApi.
 * @export
 * @interface CategoriesApiCategoriesControllerUpdateRequest
 */
export interface CategoriesApiCategoriesControllerUpdateRequest {
  /**
   * Unique identifier for the category.
   * @type {number}
   * @memberof CategoriesApiCategoriesControllerUpdate
   */
  readonly id: number;

  /**
   * New data for the category.
   * @type {UpdateCategoryDto}
   * @memberof CategoriesApiCategoriesControllerUpdate
   */
  readonly updateCategoryDto: UpdateCategoryDto;
}

/**
 * CategoriesApi - object-oriented interface
 * @export
 * @class CategoriesApi
 * @extends {BaseAPI}
 */
export class CategoriesApi extends BaseAPI implements CategoriesApiInterface {
  /**
   *
   * @summary Create a new category
   * @param {CategoriesApiCategoriesControllerCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApi
   */
  public categoriesControllerCreate(
    requestParameters: CategoriesApiCategoriesControllerCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CategoriesApiFp(this.configuration)
      .categoriesControllerCreate(requestParameters.createCategoryDto, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Gets all categories from the database.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApi
   */
  public categoriesControllerFindAll(options?: RawAxiosRequestConfig) {
    return CategoriesApiFp(this.configuration)
      .categoriesControllerFindAll(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Finds a single category.
   * @param {CategoriesApiCategoriesControllerFindOneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApi
   */
  public categoriesControllerFindOne(
    requestParameters: CategoriesApiCategoriesControllerFindOneRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CategoriesApiFp(this.configuration)
      .categoriesControllerFindOne(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Removes logically a category.
   * @param {CategoriesApiCategoriesControllerRemoveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApi
   */
  public categoriesControllerRemove(
    requestParameters: CategoriesApiCategoriesControllerRemoveRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CategoriesApiFp(this.configuration)
      .categoriesControllerRemove(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Updates a single category.
   * @param {CategoriesApiCategoriesControllerUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CategoriesApi
   */
  public categoriesControllerUpdate(
    requestParameters: CategoriesApiCategoriesControllerUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CategoriesApiFp(this.configuration)
      .categoriesControllerUpdate(
        requestParameters.id,
        requestParameters.updateCategoryDto,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
