/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { CreateEmployeeDto } from '../models';
// @ts-ignore
import type { EmployeeResponseDto } from '../models';
// @ts-ignore
import type { MessageResponseDto } from '../models';
// @ts-ignore
import type { UpdateEmployeeDto } from '../models';
/**
 * EmployeesApi - axios parameter creator
 * @export
 */
export const EmployeesApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Creates a new Employee.
     * @param {CreateEmployeeDto} createEmployeeDto Data for the new Employee.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerCreate: async (
      createEmployeeDto: CreateEmployeeDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createEmployeeDto' is not null or undefined
      assertParamExists('employeesControllerCreate', 'createEmployeeDto', createEmployeeDto);
      const localVarPath = `/employees`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createEmployeeDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Gets all the Employee from the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerFindAll: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/employees`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Find a single Employee from the database.
     * @param {number} id ID of the Employee.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerFindOne: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('employeesControllerFindOne', 'id', id);
      const localVarPath = `/employees/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Soft deletes an Employee from the database.
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerRemove: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('employeesControllerRemove', 'id', id);
      const localVarPath = `/employees/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Updates an existing Employee.
     * @param {number} id ID of the Employee.
     * @param {UpdateEmployeeDto} updateEmployeeDto The new attributes for the Employee.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerUpdate: async (
      id: number,
      updateEmployeeDto: UpdateEmployeeDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('employeesControllerUpdate', 'id', id);
      // verify required parameter 'updateEmployeeDto' is not null or undefined
      assertParamExists('employeesControllerUpdate', 'updateEmployeeDto', updateEmployeeDto);
      const localVarPath = `/employees/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateEmployeeDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * EmployeesApi - functional programming interface
 * @export
 */
export const EmployeesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = EmployeesApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Creates a new Employee.
     * @param {CreateEmployeeDto} createEmployeeDto Data for the new Employee.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async employeesControllerCreate(
      createEmployeeDto: CreateEmployeeDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeeResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.employeesControllerCreate(
        createEmployeeDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['EmployeesApi.employeesControllerCreate']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Gets all the Employee from the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async employeesControllerFindAll(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EmployeeResponseDto>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.employeesControllerFindAll(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['EmployeesApi.employeesControllerFindAll']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Find a single Employee from the database.
     * @param {number} id ID of the Employee.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async employeesControllerFindOne(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeeResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.employeesControllerFindOne(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['EmployeesApi.employeesControllerFindOne']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Soft deletes an Employee from the database.
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async employeesControllerRemove(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.employeesControllerRemove(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['EmployeesApi.employeesControllerRemove']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Updates an existing Employee.
     * @param {number} id ID of the Employee.
     * @param {UpdateEmployeeDto} updateEmployeeDto The new attributes for the Employee.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async employeesControllerUpdate(
      id: number,
      updateEmployeeDto: UpdateEmployeeDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeeResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.employeesControllerUpdate(
        id,
        updateEmployeeDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['EmployeesApi.employeesControllerUpdate']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * EmployeesApi - factory interface
 * @export
 */
export const EmployeesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = EmployeesApiFp(configuration);
  return {
    /**
     *
     * @summary Creates a new Employee.
     * @param {EmployeesApiEmployeesControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerCreate(
      requestParameters: EmployeesApiEmployeesControllerCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<EmployeeResponseDto> {
      return localVarFp
        .employeesControllerCreate(requestParameters.createEmployeeDto, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Gets all the Employee from the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerFindAll(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<EmployeeResponseDto>> {
      return localVarFp
        .employeesControllerFindAll(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Find a single Employee from the database.
     * @param {EmployeesApiEmployeesControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerFindOne(
      requestParameters: EmployeesApiEmployeesControllerFindOneRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<EmployeeResponseDto> {
      return localVarFp
        .employeesControllerFindOne(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Soft deletes an Employee from the database.
     * @param {EmployeesApiEmployeesControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerRemove(
      requestParameters: EmployeesApiEmployeesControllerRemoveRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<MessageResponseDto> {
      return localVarFp
        .employeesControllerRemove(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Updates an existing Employee.
     * @param {EmployeesApiEmployeesControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    employeesControllerUpdate(
      requestParameters: EmployeesApiEmployeesControllerUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<EmployeeResponseDto> {
      return localVarFp
        .employeesControllerUpdate(
          requestParameters.id,
          requestParameters.updateEmployeeDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * EmployeesApi - interface
 * @export
 * @interface EmployeesApi
 */
export interface EmployeesApiInterface {
  /**
   *
   * @summary Creates a new Employee.
   * @param {EmployeesApiEmployeesControllerCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApiInterface
   */
  employeesControllerCreate(
    requestParameters: EmployeesApiEmployeesControllerCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<EmployeeResponseDto>;

  /**
   *
   * @summary Gets all the Employee from the database.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApiInterface
   */
  employeesControllerFindAll(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Array<EmployeeResponseDto>>;

  /**
   *
   * @summary Find a single Employee from the database.
   * @param {EmployeesApiEmployeesControllerFindOneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApiInterface
   */
  employeesControllerFindOne(
    requestParameters: EmployeesApiEmployeesControllerFindOneRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<EmployeeResponseDto>;

  /**
   *
   * @summary Soft deletes an Employee from the database.
   * @param {EmployeesApiEmployeesControllerRemoveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApiInterface
   */
  employeesControllerRemove(
    requestParameters: EmployeesApiEmployeesControllerRemoveRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<MessageResponseDto>;

  /**
   *
   * @summary Updates an existing Employee.
   * @param {EmployeesApiEmployeesControllerUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApiInterface
   */
  employeesControllerUpdate(
    requestParameters: EmployeesApiEmployeesControllerUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<EmployeeResponseDto>;
}

/**
 * Request parameters for employeesControllerCreate operation in EmployeesApi.
 * @export
 * @interface EmployeesApiEmployeesControllerCreateRequest
 */
export interface EmployeesApiEmployeesControllerCreateRequest {
  /**
   * Data for the new Employee.
   * @type {CreateEmployeeDto}
   * @memberof EmployeesApiEmployeesControllerCreate
   */
  readonly createEmployeeDto: CreateEmployeeDto;
}

/**
 * Request parameters for employeesControllerFindOne operation in EmployeesApi.
 * @export
 * @interface EmployeesApiEmployeesControllerFindOneRequest
 */
export interface EmployeesApiEmployeesControllerFindOneRequest {
  /**
   * ID of the Employee.
   * @type {number}
   * @memberof EmployeesApiEmployeesControllerFindOne
   */
  readonly id: number;
}

/**
 * Request parameters for employeesControllerRemove operation in EmployeesApi.
 * @export
 * @interface EmployeesApiEmployeesControllerRemoveRequest
 */
export interface EmployeesApiEmployeesControllerRemoveRequest {
  /**
   *
   * @type {number}
   * @memberof EmployeesApiEmployeesControllerRemove
   */
  readonly id: number;
}

/**
 * Request parameters for employeesControllerUpdate operation in EmployeesApi.
 * @export
 * @interface EmployeesApiEmployeesControllerUpdateRequest
 */
export interface EmployeesApiEmployeesControllerUpdateRequest {
  /**
   * ID of the Employee.
   * @type {number}
   * @memberof EmployeesApiEmployeesControllerUpdate
   */
  readonly id: number;

  /**
   * The new attributes for the Employee.
   * @type {UpdateEmployeeDto}
   * @memberof EmployeesApiEmployeesControllerUpdate
   */
  readonly updateEmployeeDto: UpdateEmployeeDto;
}

/**
 * EmployeesApi - object-oriented interface
 * @export
 * @class EmployeesApi
 * @extends {BaseAPI}
 */
export class EmployeesApi extends BaseAPI implements EmployeesApiInterface {
  /**
   *
   * @summary Creates a new Employee.
   * @param {EmployeesApiEmployeesControllerCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApi
   */
  public employeesControllerCreate(
    requestParameters: EmployeesApiEmployeesControllerCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return EmployeesApiFp(this.configuration)
      .employeesControllerCreate(requestParameters.createEmployeeDto, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Gets all the Employee from the database.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApi
   */
  public employeesControllerFindAll(options?: RawAxiosRequestConfig) {
    return EmployeesApiFp(this.configuration)
      .employeesControllerFindAll(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Find a single Employee from the database.
   * @param {EmployeesApiEmployeesControllerFindOneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApi
   */
  public employeesControllerFindOne(
    requestParameters: EmployeesApiEmployeesControllerFindOneRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return EmployeesApiFp(this.configuration)
      .employeesControllerFindOne(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Soft deletes an Employee from the database.
   * @param {EmployeesApiEmployeesControllerRemoveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApi
   */
  public employeesControllerRemove(
    requestParameters: EmployeesApiEmployeesControllerRemoveRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return EmployeesApiFp(this.configuration)
      .employeesControllerRemove(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Updates an existing Employee.
   * @param {EmployeesApiEmployeesControllerUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EmployeesApi
   */
  public employeesControllerUpdate(
    requestParameters: EmployeesApiEmployeesControllerUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return EmployeesApiFp(this.configuration)
      .employeesControllerUpdate(requestParameters.id, requestParameters.updateEmployeeDto, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
