/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { CreateRoleDto } from '../models';
// @ts-ignore
import type { RoleResponseDto } from '../models';
// @ts-ignore
import type { UpdateRoleDto } from '../models';
/**
 * RolesApi - axios parameter creator
 * @export
 */
export const RolesApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Creates a new role in the database.
     * @param {CreateRoleDto} createRoleDto The data for the new role
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rolesControllerCreate: async (
      createRoleDto: CreateRoleDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createRoleDto' is not null or undefined
      assertParamExists('rolesControllerCreate', 'createRoleDto', createRoleDto);
      const localVarPath = `/roles`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createRoleDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Finds all the valid roles in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rolesControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/roles`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Finds a single instance of valid role by the ID.
     * @param {number} id The unique identifier of the role in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rolesControllerFindOne: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('rolesControllerFindOne', 'id', id);
      const localVarPath = `/roles/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Updates an already existing role in the database.
     * @param {number} id The unique identifier of the role in the database.
     * @param {UpdateRoleDto} updateRoleDto The new data for the role.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rolesControllerUpdate: async (
      id: number,
      updateRoleDto: UpdateRoleDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('rolesControllerUpdate', 'id', id);
      // verify required parameter 'updateRoleDto' is not null or undefined
      assertParamExists('rolesControllerUpdate', 'updateRoleDto', updateRoleDto);
      const localVarPath = `/roles/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateRoleDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * RolesApi - functional programming interface
 * @export
 */
export const RolesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = RolesApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Creates a new role in the database.
     * @param {CreateRoleDto} createRoleDto The data for the new role
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async rolesControllerCreate(
      createRoleDto: CreateRoleDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.rolesControllerCreate(
        createRoleDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['RolesApi.rolesControllerCreate']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Finds all the valid roles in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async rolesControllerFindAll(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RoleResponseDto>>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.rolesControllerFindAll(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['RolesApi.rolesControllerFindAll']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Finds a single instance of valid role by the ID.
     * @param {number} id The unique identifier of the role in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async rolesControllerFindOne(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.rolesControllerFindOne(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['RolesApi.rolesControllerFindOne']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Updates an already existing role in the database.
     * @param {number} id The unique identifier of the role in the database.
     * @param {UpdateRoleDto} updateRoleDto The new data for the role.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async rolesControllerUpdate(
      id: number,
      updateRoleDto: UpdateRoleDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.rolesControllerUpdate(
        id,
        updateRoleDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['RolesApi.rolesControllerUpdate']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * RolesApi - factory interface
 * @export
 */
export const RolesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = RolesApiFp(configuration);
  return {
    /**
     *
     * @summary Creates a new role in the database.
     * @param {RolesApiRolesControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rolesControllerCreate(
      requestParameters: RolesApiRolesControllerCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RoleResponseDto> {
      return localVarFp
        .rolesControllerCreate(requestParameters.createRoleDto, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Finds all the valid roles in the database.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rolesControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<RoleResponseDto>> {
      return localVarFp.rolesControllerFindAll(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Finds a single instance of valid role by the ID.
     * @param {RolesApiRolesControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rolesControllerFindOne(
      requestParameters: RolesApiRolesControllerFindOneRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RoleResponseDto> {
      return localVarFp
        .rolesControllerFindOne(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Updates an already existing role in the database.
     * @param {RolesApiRolesControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rolesControllerUpdate(
      requestParameters: RolesApiRolesControllerUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RoleResponseDto> {
      return localVarFp
        .rolesControllerUpdate(requestParameters.id, requestParameters.updateRoleDto, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * RolesApi - interface
 * @export
 * @interface RolesApi
 */
export interface RolesApiInterface {
  /**
   *
   * @summary Creates a new role in the database.
   * @param {RolesApiRolesControllerCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RolesApiInterface
   */
  rolesControllerCreate(
    requestParameters: RolesApiRolesControllerCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<RoleResponseDto>;

  /**
   *
   * @summary Finds all the valid roles in the database.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RolesApiInterface
   */
  rolesControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<RoleResponseDto>>;

  /**
   *
   * @summary Finds a single instance of valid role by the ID.
   * @param {RolesApiRolesControllerFindOneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RolesApiInterface
   */
  rolesControllerFindOne(
    requestParameters: RolesApiRolesControllerFindOneRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<RoleResponseDto>;

  /**
   *
   * @summary Updates an already existing role in the database.
   * @param {RolesApiRolesControllerUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RolesApiInterface
   */
  rolesControllerUpdate(
    requestParameters: RolesApiRolesControllerUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<RoleResponseDto>;
}

/**
 * Request parameters for rolesControllerCreate operation in RolesApi.
 * @export
 * @interface RolesApiRolesControllerCreateRequest
 */
export interface RolesApiRolesControllerCreateRequest {
  /**
   * The data for the new role
   * @type {CreateRoleDto}
   * @memberof RolesApiRolesControllerCreate
   */
  readonly createRoleDto: CreateRoleDto;
}

/**
 * Request parameters for rolesControllerFindOne operation in RolesApi.
 * @export
 * @interface RolesApiRolesControllerFindOneRequest
 */
export interface RolesApiRolesControllerFindOneRequest {
  /**
   * The unique identifier of the role in the database.
   * @type {number}
   * @memberof RolesApiRolesControllerFindOne
   */
  readonly id: number;
}

/**
 * Request parameters for rolesControllerUpdate operation in RolesApi.
 * @export
 * @interface RolesApiRolesControllerUpdateRequest
 */
export interface RolesApiRolesControllerUpdateRequest {
  /**
   * The unique identifier of the role in the database.
   * @type {number}
   * @memberof RolesApiRolesControllerUpdate
   */
  readonly id: number;

  /**
   * The new data for the role.
   * @type {UpdateRoleDto}
   * @memberof RolesApiRolesControllerUpdate
   */
  readonly updateRoleDto: UpdateRoleDto;
}

/**
 * RolesApi - object-oriented interface
 * @export
 * @class RolesApi
 * @extends {BaseAPI}
 */
export class RolesApi extends BaseAPI implements RolesApiInterface {
  /**
   *
   * @summary Creates a new role in the database.
   * @param {RolesApiRolesControllerCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RolesApi
   */
  public rolesControllerCreate(
    requestParameters: RolesApiRolesControllerCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return RolesApiFp(this.configuration)
      .rolesControllerCreate(requestParameters.createRoleDto, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Finds all the valid roles in the database.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RolesApi
   */
  public rolesControllerFindAll(options?: RawAxiosRequestConfig) {
    return RolesApiFp(this.configuration)
      .rolesControllerFindAll(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Finds a single instance of valid role by the ID.
   * @param {RolesApiRolesControllerFindOneRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RolesApi
   */
  public rolesControllerFindOne(
    requestParameters: RolesApiRolesControllerFindOneRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return RolesApiFp(this.configuration)
      .rolesControllerFindOne(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Updates an already existing role in the database.
   * @param {RolesApiRolesControllerUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RolesApi
   */
  public rolesControllerUpdate(
    requestParameters: RolesApiRolesControllerUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return RolesApiFp(this.configuration)
      .rolesControllerUpdate(requestParameters.id, requestParameters.updateRoleDto, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
