/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { AssetsMetricsDto } from '../models';
/**
 * StatisticsApi - axios parameter creator
 * @export
 */
export const StatisticsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Returns aggregate metrics about assets (totals, availability, popular category).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    statisticsControllerAssetsMetrics: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/statistics/assets-metrics`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * StatisticsApi - functional programming interface
 * @export
 */
export const StatisticsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = StatisticsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Returns aggregate metrics about assets (totals, availability, popular category).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async statisticsControllerAssetsMetrics(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AssetsMetricsDto>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.statisticsControllerAssetsMetrics(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['StatisticsApi.statisticsControllerAssetsMetrics']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * StatisticsApi - factory interface
 * @export
 */
export const StatisticsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = StatisticsApiFp(configuration);
  return {
    /**
     *
     * @summary Returns aggregate metrics about assets (totals, availability, popular category).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    statisticsControllerAssetsMetrics(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AssetsMetricsDto> {
      return localVarFp
        .statisticsControllerAssetsMetrics(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * StatisticsApi - interface
 * @export
 * @interface StatisticsApi
 */
export interface StatisticsApiInterface {
  /**
   *
   * @summary Returns aggregate metrics about assets (totals, availability, popular category).
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StatisticsApiInterface
   */
  statisticsControllerAssetsMetrics(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<AssetsMetricsDto>;
}

/**
 * StatisticsApi - object-oriented interface
 * @export
 * @class StatisticsApi
 * @extends {BaseAPI}
 */
export class StatisticsApi extends BaseAPI implements StatisticsApiInterface {
  /**
   *
   * @summary Returns aggregate metrics about assets (totals, availability, popular category).
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StatisticsApi
   */
  public statisticsControllerAssetsMetrics(options?: RawAxiosRequestConfig) {
    return StatisticsApiFp(this.configuration)
      .statisticsControllerAssetsMetrics(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
