/* tslint:disable */

/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AssetCreationTimeSeriesPointDto
 */
export interface AssetCreationTimeSeriesPointDto {
  /**
   * English name of the calendar month
   * @type {string}
   * @memberof AssetCreationTimeSeriesPointDto
   */
  month: string;
  /**
   * Number of (non-deleted) assets created in that month for the requested year
   * @type {number}
   * @memberof AssetCreationTimeSeriesPointDto
   */
  total: number;
}
