/* tslint:disable */

/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AssetsMetricsDto
 */
export interface AssetsMetricsDto {
  /**
   * Total number of non-deleted assets in the system
   * @type {number}
   * @memberof AssetsMetricsDto
   */
  total: number;
  /**
   * Number of assets that are not assigned to any employee
   * @type {number}
   * @memberof AssetsMetricsDto
   */
  availables: number;
  /**
   * Number of assets currently assigned to an employee
   * @type {number}
   * @memberof AssetsMetricsDto
   */
  assigned: number;
  /**
   * Share of assets that are unassigned, as a percentage (0–100)
   * @type {number}
   * @memberof AssetsMetricsDto
   */
  disponibility: number;
  /**
   * Name of the category that holds the most assets; N/A when there are no categories
   * @type {string}
   * @memberof AssetsMetricsDto
   */
  popularCategory: string;
}
