/* tslint:disable */

/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateRoleDto
 */
export interface UpdateRoleDto {
  /**
   * Unique role code in the application level
   * @type {string}
   * @memberof UpdateRoleDto
   */
  roleCode?: string;
  /**
   * Official name for the role in user level
   * @type {string}
   * @memberof UpdateRoleDto
   */
  name?: string;
  /**
   * Description for the role in user level
   * @type {string}
   * @memberof UpdateRoleDto
   */
  description?: string;
}
