/* tslint:disable */

/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './apis/app-api';
export * from './apis/assets-api';
export * from './apis/categories-api';
export * from './apis/employees-api';
export * from './apis/roles-api';
export * from './apis/statistics-api';
